### ISSUE TITLE
Can't do `run_cnn_synthesis.py`

### ISSUE THREAD

**Issue by rgga-16** [ahoudard/wgenpatex#1] opened 2022-10-03 09:14 UTC
I get this error

```
Traceback (most recent call last):
  File "run_cnn_synthesis.py", line 19, in <module>
    generator = wgenpatex.learn_model(args)
  File "C:/Users/r-gal/OneDrive/Desktop/wgenpatex/wgenpatex.py", line 329, in learn_model
    layer = semidual(real_data, usekeops)
  File "C:/Users/r-gal/OneDrive/Desktop/wgenpatex/wgenpatex.py", line 91, in __init__
    self.psi = nn.Parameter(torch.zeros(inputy.shape[0], device=device))
TypeError: zeros() received an invalid combination of arguments - got (int, device=bool), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
```

**Comment by ahoudard** [comment] 2022-10-10 08:43
Indeed, there was an issue with imputing the device properly in the semidual function. 
The issue is now fixed.

**Closed as completed by ahoudard** 2022-10-10 08:43 UTC
